In [12]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd

def b_print(df , n=30 , clean=True):
    
    # from IPython.display import display, HTML

    if clean : # remove tickers da mesma empresa, deixando a primeria ocorrencia
        df['prefixo'] = df['Papel'].astype(str).str[:4]
        df=df.drop_duplicates(subset='prefixo', keep='first')
        # df=df.drop('prefixo', axis=1) 
    
    display(HTML(df.head(n).to_html(index=False)))
    df = None

In [13]:
# A empresa e Indicadores fundamentalistas dados do statusinvest.com.br
#(pode ter atraso, dados não são pegos diretamente no SI)

url = 'https://raw.githubusercontent.com/BDonadelli/Codigos-em-financas/main/data/SI_Acoes.csv'
pd.set_option('display.max_columns', None)
fundsSI = pd.read_csv(url,sep=';' , decimal=',' ,thousands ='.' )

In [14]:
fundsSI.columns

Index(['TICKER', 'PRECO', 'DY', 'P/L', 'P/VP', 'P/ATIVOS', 'MARGEM BRUTA',
       'MARGEM EBIT', 'MARG. LIQUIDA', 'P/EBIT', 'EV/EBIT',
       'DIVIDA LIQUIDA / EBIT', 'DIV. LIQ. / PATRI.', 'PSR', 'P/CAP. GIRO',
       'P. AT CIR. LIQ.', 'LIQ. CORRENTE', 'ROE', 'ROA', 'ROIC',
       'PATRIMONIO / ATIVOS', 'PASSIVOS / ATIVOS', 'GIRO ATIVOS',
       'CAGR RECEITAS 5 ANOS', 'CAGR LUCROS 5 ANOS', ' LIQUIDEZ MEDIA DIARIA',
       ' VPA', ' LPA', ' PEG Ratio', ' VALOR DE MERCADO'],
      dtype='object')

In [15]:
fundsSI =  fundsSI[fundsSI[' LIQUIDEZ MEDIA DIARIA'] > 250000] 
fundsSI =  fundsSI[(fundsSI[' LPA'] > 0) & (fundsSI[' VPA'] > 0) ]
# fundsSI

In [16]:
fundsSI['valor_intrinseco'] = np.sqrt(22.5 * fundsSI[' LPA'] * fundsSI[' VPA'])
fundsSI['Delta'] = fundsSI['valor_intrinseco'] / fundsSI['PRECO'] -1
fundsSI["Rank"]   = fundsSI['Delta'].rank(ascending=True, method="min")
fundsSI.sort_values(by="Rank", ascending=False, inplace=True)
fundsSI.reset_index(inplace=True)
fundsSI.index = fundsSI.index + 1

top20 = fundsSI[['TICKER','PRECO' , 'valor_intrinseco' , 'Rank' , 'Delta' , ' LPA' , ' VPA' ]].head(20)
top20

   TICKER  PRECO  valor_intrinseco   Rank     Delta   LPA    VPA
1   LUPA3   1.53          8.703749  200.0  4.688725  0.87   3.87
2   MEAL3   1.54          5.982725  199.0  2.884886  0.41   3.88
3   HBOR3   2.70          8.386596  198.0  2.106147  0.30  10.42
4   GOAU4  10.52         32.252023  197.0  2.065782  2.66  17.38
5   GOAU3  10.72         32.252023  196.0  2.008584  2.66  17.38
6   MTRE3   4.42         13.056722  195.0  1.954010  0.82   9.24
7   GGBR3  16.24         45.655230  194.0  1.811283  3.86  24.00
8   BRSR6  12.60         34.915348  193.0  1.771059  2.29  23.66
9   HBRE3   5.28         14.570089  192.0  1.759487  0.51  18.50
10  TCSA3   2.38          6.304641  191.0  1.649009  0.22   8.03
11  COCE5  35.70         92.970298  190.0  1.604210  7.05  54.49
12  ALOS3  21.60         56.101845  189.0  1.597308  5.46  25.62
13  EUCA4  15.43         39.888636  188.0  1.585135  2.97  23.81
14  NEOE3  19.31         48.354565  187.0  1.504120  4.28  24.28
15  GGBR4  18.36         45.655230  186.0  1.486668  3.86  24.00
16  JALL3   7.10         17.548333  185.0  1.471596  2.08   6.58
17  BRAP3  20.17         49.797741  184.0  1.468901  5.40  20.41
18  BMGB4   3.21          7.791341  183.0  1.427209  0.38   7.10
19  NTCO3  16.44         39.493123  182.0  1.402258  3.43  20.21
20  SAPR3   5.01         11.827383  181.0  1.360755  0.99   6.28

In [17]:
fundsSI =  fundsSI[(fundsSI['P/L'] > 0)]
top20 = fundsSI[['TICKER','PRECO' , 'valor_intrinseco' , 'Rank' , 'Delta' , ' LPA' , ' VPA' ]].head(20)
top20

   TICKER  PRECO  valor_intrinseco   Rank     Delta   LPA    VPA
1   LUPA3   1.53          8.703749  200.0  4.688725  0.87   3.87
2   MEAL3   1.54          5.982725  199.0  2.884886  0.41   3.88
3   HBOR3   2.70          8.386596  198.0  2.106147  0.30  10.42
4   GOAU4  10.52         32.252023  197.0  2.065782  2.66  17.38
5   GOAU3  10.72         32.252023  196.0  2.008584  2.66  17.38
6   MTRE3   4.42         13.056722  195.0  1.954010  0.82   9.24
7   GGBR3  16.24         45.655230  194.0  1.811283  3.86  24.00
8   BRSR6  12.60         34.915348  193.0  1.771059  2.29  23.66
9   HBRE3   5.28         14.570089  192.0  1.759487  0.51  18.50
10  TCSA3   2.38          6.304641  191.0  1.649009  0.22   8.03
11  COCE5  35.70         92.970298  190.0  1.604210  7.05  54.49
12  ALOS3  21.60         56.101845  189.0  1.597308  5.46  25.62
13  EUCA4  15.43         39.888636  188.0  1.585135  2.97  23.81
14  NEOE3  19.31         48.354565  187.0  1.504120  4.28  24.28
15  GGBR4  18.36         45.655230  186.0  1.486668  3.86  24.00
16  JALL3   7.10         17.548333  185.0  1.471596  2.08   6.58
17  BRAP3  20.17         49.797741  184.0  1.468901  5.40  20.41
18  BMGB4   3.21          7.791341  183.0  1.427209  0.38   7.10
19  NTCO3  16.44         39.493123  182.0  1.402258  3.43  20.21
20  SAPR3   5.01         11.827383  181.0  1.360755  0.99   6.28

In [18]:
fundsSI =  fundsSI[(fundsSI['CAGR RECEITAS 5 ANOS'] > 0) ]
top20 = fundsSI[['TICKER','PRECO' , 'valor_intrinseco' , 'Rank' , 'Delta' , ' LPA' , ' VPA' ]].head(20)
top20

    TICKER  PRECO  valor_intrinseco   Rank     Delta   LPA    VPA
2    MEAL3   1.54          5.982725  199.0  2.884886  0.41   3.88
3    HBOR3   2.70          8.386596  198.0  2.106147  0.30  10.42
4    GOAU4  10.52         32.252023  197.0  2.065782  2.66  17.38
5    GOAU3  10.72         32.252023  196.0  2.008584  2.66  17.38
6    MTRE3   4.42         13.056722  195.0  1.954010  0.82   9.24
7    GGBR3  16.24         45.655230  194.0  1.811283  3.86  24.00
8    BRSR6  12.60         34.915348  193.0  1.771059  2.29  23.66
9    HBRE3   5.28         14.570089  192.0  1.759487  0.51  18.50
11   COCE5  35.70         92.970298  190.0  1.604210  7.05  54.49
12   ALOS3  21.60         56.101845  189.0  1.597308  5.46  25.62
13   EUCA4  15.43         39.888636  188.0  1.585135  2.97  23.81
14   NEOE3  19.31         48.354565  187.0  1.504120  4.28  24.28
15   GGBR4  18.36         45.655230  186.0  1.486668  3.86  24.00
18   BMGB4   3.21          7.791341  183.0  1.427209  0.38   7.10
19   NTCO3  16.44         39.493123  182.0  1.402258  3.43  20.21
20   SAPR3   5.01         11.827383  181.0  1.360755  0.99   6.28
22   JHSF3   4.21          9.840274  179.0  1.337357  0.58   7.42
23  SAPR11  26.07         59.036120  178.0  1.264523  4.93  31.42
24   ALLD3   7.71         17.398772  177.0  1.256650  0.81  16.61
25   SAPR4   5.28         11.827383  176.0  1.240035  0.99   6.28

In [19]:
fundsSI =  fundsSI[(fundsSI['CAGR LUCROS 5 ANOS'] > 0) ]
top20 = fundsSI[['TICKER','PRECO' , 'valor_intrinseco' , 'Rank' , 'Delta' , ' LPA' , ' VPA' ]].head(20)
top20

    TICKER   PRECO  valor_intrinseco   Rank     Delta    LPA     VPA
2    MEAL3    1.54          5.982725  199.0  2.884886   0.41    3.88
11   COCE5   35.70         92.970298  190.0  1.604210   7.05   54.49
12   ALOS3   21.60         56.101845  189.0  1.597308   5.46   25.62
13   EUCA4   15.43         39.888636  188.0  1.585135   2.97   23.81
14   NEOE3   19.31         48.354565  187.0  1.504120   4.28   24.28
18   BMGB4    3.21          7.791341  183.0  1.427209   0.38    7.10
19   NTCO3   16.44         39.493123  182.0  1.402258   3.43   20.21
20   SAPR3    5.01         11.827383  181.0  1.360755   0.99    6.28
23  SAPR11   26.07         59.036120  178.0  1.264523   4.93   31.42
24   ALLD3    7.71         17.398772  177.0  1.256650   0.81   16.61
25   SAPR4    5.28         11.827383  176.0  1.240035   0.99    6.28
26   BBAS3   27.58         61.369783  175.0  1.225155   5.79   28.91
29   CMIG4   12.84         27.554310  172.0  1.145974   3.04   11.10
30   BAZA3  104.99        222.951056  171.0  1.123546  21.31  103.67
31   ROMI3   10.53         21.952950  170.0  1.084801   1.76   12.17
32   FESA4    8.15         16.778558  169.0  1.058719   1.36    9.20
33   TRIS3    4.66          9.569248  168.0  1.053487   0.57    7.14
34   ABCB4   23.07         47.142377  167.0  1.043449   4.09   24.15
39   CAML3    8.36         16.312526  162.0  0.951259   1.38    8.57
42   TRPL4   24.74         46.941900  159.0  0.897409   3.59   27.28

In [20]:
fundsSI =  fundsSI[(fundsSI['DIVIDA LIQUIDA / EBIT'] <4) ]
top20 = fundsSI[['TICKER','PRECO' , 'valor_intrinseco' , 'Rank' , 'Delta' , ' LPA' , ' VPA' ]].head(20)
top20

    TICKER  PRECO  valor_intrinseco   Rank     Delta    LPA    VPA
2    MEAL3   1.54          5.982725  199.0  2.884886   0.41   3.88
12   ALOS3  21.60         56.101845  189.0  1.597308   5.46  25.62
13   EUCA4  15.43         39.888636  188.0  1.585135   2.97  23.81
14   NEOE3  19.31         48.354565  187.0  1.504120   4.28  24.28
19   NTCO3  16.44         39.493123  182.0  1.402258   3.43  20.21
20   SAPR3   5.01         11.827383  181.0  1.360755   0.99   6.28
23  SAPR11  26.07         59.036120  178.0  1.264523   4.93  31.42
24   ALLD3   7.71         17.398772  177.0  1.256650   0.81  16.61
25   SAPR4   5.28         11.827383  176.0  1.240035   0.99   6.28
29   CMIG4  12.84         27.554310  172.0  1.145974   3.04  11.10
31   ROMI3  10.53         21.952950  170.0  1.084801   1.76  12.17
32   FESA4   8.15         16.778558  169.0  1.058719   1.36   9.20
33   TRIS3   4.66          9.569248  168.0  1.053487   0.57   7.14
39   CAML3   8.36         16.312526  162.0  0.951259   1.38   8.57
42   TRPL4  24.74         46.941900  159.0  0.897409   3.59  27.28
43   CMIG3  14.83         27.554310  158.0  0.858011   3.04  11.10
45   CSMG3  21.53         39.841875  156.0  0.850528   3.40  20.75
46   DXCO3   7.14         13.189683  155.0  0.847295   0.99   7.81
50   VLID3  17.63         30.373426  151.0  0.722826   2.47  16.60
54   SUZB3  60.36         97.000397  147.0  0.607031  13.06  32.02

In [21]:
fundsSI['prefixo'] = fundsSI['TICKER'].str[:4]
fundsSI.drop_duplicates(subset='prefixo', keep='first').head(20)
df_limpo = fundsSI.drop_duplicates(subset='prefixo', keep='first')
df_limpo = df_limpo.drop('prefixo', axis=1) 
df_limpo[['TICKER','PRECO' , 'valor_intrinseco' , 'Rank' , 'Delta' , ' LPA' , ' VPA' ]].head(20)

   TICKER  PRECO  valor_intrinseco   Rank     Delta    LPA    VPA
2   MEAL3   1.54          5.982725  199.0  2.884886   0.41   3.88
12  ALOS3  21.60         56.101845  189.0  1.597308   5.46  25.62
13  EUCA4  15.43         39.888636  188.0  1.585135   2.97  23.81
14  NEOE3  19.31         48.354565  187.0  1.504120   4.28  24.28
19  NTCO3  16.44         39.493123  182.0  1.402258   3.43  20.21
20  SAPR3   5.01         11.827383  181.0  1.360755   0.99   6.28
24  ALLD3   7.71         17.398772  177.0  1.256650   0.81  16.61
29  CMIG4  12.84         27.554310  172.0  1.145974   3.04  11.10
31  ROMI3  10.53         21.952950  170.0  1.084801   1.76  12.17
32  FESA4   8.15         16.778558  169.0  1.058719   1.36   9.20
33  TRIS3   4.66          9.569248  168.0  1.053487   0.57   7.14
39  CAML3   8.36         16.312526  162.0  0.951259   1.38   8.57
42  TRPL4  24.74         46.941900  159.0  0.897409   3.59  27.28
45  CSMG3  21.53         39.841875  156.0  0.850528   3.40  20.75
46  DXCO3   7.14         13.189683  155.0  0.847295   0.99   7.81
50  VLID3  17.63         30.373426  151.0  0.722826   2.47  16.60
54  SUZB3  60.36         97.000397  147.0  0.607031  13.06  32.02
55  RAPT3   9.92         15.920082  146.0  0.604847   1.26   8.94
56  ITSA4   9.60         15.256408  145.0  0.589209   1.34   7.72
60  PDTC3   2.27          3.548697  141.0  0.563303   0.29   1.93

In [22]:
# linhas_com_nan = top20[top20.isna().any(axis=1)]
# linhas_com_nan

### Porque 22,5?

O número 22,5 na Fórmula de Graham é um fator de ponderação que tem um propósito específico. Essa constante foi escolhida por Graham pra ajustar a avaliação do preço justo de uma ação com base na taxa de crescimento anual esperada da empresa.

O número 22,5 é, na verdade, o resultado da multiplicação de 8,5 por 2,65 (8,5 x 2,65 = 22,5). O número 8,5 é a base que Graham considerou razoável pra uma empresa com taxa de crescimento zero, ou seja, uma empresa que não cresce.

Já o número 2,65 representa a média do retorno exigido pelos investidores no mercado de ações durante a época de Graham, que era de aproximadamente 4,4% acima da taxa de retorno dos títulos do Tesouro dos Estados Unidos.

O fator 22,5 ajuda a ajustar o preço justo com base no crescimento da empresa e na expectativa de retorno dos investidores.

Esse ajuste garante que a Fórmula de Graham considere a taxa de crescimento anual esperada e reflita uma avaliação mais realista do preço justo de uma ação.

No próximo tópico, abordaremos a calculadora do preço justo usando a Fórmula de Graham.